import type { ProjectData } from '@/types/project'

export interface Template {
  id: string
  name: string
  category: string
  description: string
  emoji: string
  isPremium: boolean
  config: Partial<ProjectData>
}

export const TEMPLATES: Template[] = [
  {
    id: 'neon-lyrics',
    name: 'Neon Lyrics',
    category: 'Hip-hop / Trap',
    description: 'Texto neón sobre fondo oscuro con glow violeta. Ideal para rap y trap.',
    emoji: '🟣',
    isPremium: false,
    config: {
      background: { type: 'color', color: '#05050a', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: 'Inter',
        fontSize: 72,
        color: '#ffffff',
        glow: true,
        glowColor: '#9f5fff',
        animation: 'bounce',
        translationColor: '#7c3aed',
        translationSize: 36,
      },
      particles: { enabled: true, count: 200, reactTo: 'treble', color: '#7c3aed', size: 0.04 },
      heroShape: {
        enabled: false,
        type: 'torusKnot',
        style: 'solid',
        colorA: '#a855f7',
        colorB: '#22d3ee',
        wireframeColor: '#67e8f9',
        knotP: 2,
        knotQ: 5,
        reactTo: 'bass',
      },
    },
  },
  {
    id: 'space-visualizer',
    name: 'Space Visualizer',
    category: 'Electronic / Ambient',
    description: 'Galaxia de partículas con frecuencias reactivas. Perfecto para music art.',
    emoji: '🌌',
    isPremium: false,
    config: {
      background: { type: 'color', color: '#000510', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: 'Inter',
        fontSize: 56,
        color: '#c8e6ff',
        glow: true,
        glowColor: '#38bdf8',
        animation: 'fade',
        translationColor: '#7dd3fc',
        translationSize: 28,
      },
      particles: { enabled: true, count: 500, reactTo: 'bass', color: '#38bdf8', size: 0.03 },
      heroShape: {
        enabled: false,
        type: 'torusKnot',
        style: 'solid',
        colorA: '#a855f7',
        colorB: '#22d3ee',
        wireframeColor: '#67e8f9',
        knotP: 2,
        knotQ: 5,
        reactTo: 'bass',
      },
    },
  },
  {
    id: 'phonk-glitch',
    name: 'Phonk Glitch',
    category: 'Phonk / Dark Trap',
    description: 'Rojo y negro con efecto glitch en los kicks. Brutal.',
    emoji: '💀',
    isPremium: false,
    config: {
      background: { type: 'color', color: '#0a0000', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: 'Inter',
        fontSize: 80,
        color: '#ff2020',
        glow: true,
        glowColor: '#ff0000',
        animation: 'slide',
        translationColor: '#ff6060',
        translationSize: 40,
      },
      particles: { enabled: true, count: 300, reactTo: 'bass', color: '#ff2020', size: 0.05 },
      heroShape: {
        enabled: false,
        type: 'torusKnot',
        style: 'solid',
        colorA: '#a855f7',
        colorB: '#22d3ee',
        wireframeColor: '#67e8f9',
        knotP: 2,
        knotQ: 5,
        reactTo: 'bass',
      },
    },
  },
  {
    id: 'dark-cinematic',
    name: 'Dark Cinematic',
    category: 'R&B / Ballads',
    description: 'Cinematográfico con tones dorados. Elegante y oscuro.',
    emoji: '🎬',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#080604', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: 'Inter',
        fontSize: 60,
        color: '#f5d98a',
        glow: true,
        glowColor: '#d4a017',
        animation: 'fade',
        translationColor: '#b8924e',
        translationSize: 30,
      },
      particles: { enabled: false, count: 100, reactTo: 'mid', color: '#f5d98a', size: 0.02 },
      heroShape: {
        enabled: false,
        type: 'torusKnot',
        style: 'solid',
        colorA: '#a855f7',
        colorB: '#22d3ee',
        wireframeColor: '#67e8f9',
        knotP: 2,
        knotQ: 5,
        reactTo: 'bass',
      },
    },
  },
  {
    id: 'karaoke-clean',
    name: 'Karaoke Clean',
    category: 'Pop / J-pop',
    description: 'Letras limpias centradas con fondo blanco. Minimalista y fresco.',
    emoji: '🎤',
    isPremium: false,
    config: {
      background: { type: 'color', color: '#f0f0f8', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: 'Inter',
        fontSize: 64,
        color: '#1a1a2e',
        glow: false,
        glowColor: '#6366f1',
        animation: 'karaoke',
        translationColor: '#6366f1',
        translationSize: 32,
      },
      particles: { enabled: false, count: 0, reactTo: 'treble', color: '#6366f1', size: 0.02 },
      heroShape: {
        enabled: false,
        type: 'torusKnot',
        style: 'solid',
        colorA: '#a855f7',
        colorB: '#22d3ee',
        wireframeColor: '#67e8f9',
        knotP: 2,
        knotQ: 5,
        reactTo: 'bass',
      },
    },
  },
  {
    id: 'lofi-rain',
    name: 'Lo-Fi Rain',
    category: 'Lo-fi / Chill',
    description: 'Colores pasteles con efecto lluvia. Perfecto para chill beats.',
    emoji: '🌧️',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#1a1a2e', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: 'Inter',
        fontSize: 52,
        color: '#fde8d8',
        glow: true,
        glowColor: '#f9a8d4',
        animation: 'fade',
        translationColor: '#fbcfe8',
        translationSize: 26,
      },
      particles: { enabled: true, count: 400, reactTo: 'treble', color: '#93c5fd', size: 0.02 },
      heroShape: {
        enabled: false,
        type: 'torusKnot',
        style: 'solid',
        colorA: '#a855f7',
        colorB: '#22d3ee',
        wireframeColor: '#67e8f9',
        knotP: 2,
        knotQ: 5,
        reactTo: 'bass',
      },
    },
  },
  {
    id: 'cyberpunk-city',
    name: 'Cyberpunk City',
    category: 'Synthwave / EDM',
    description: 'Ciudad futurista con neón cyan y magenta. Alta energía.',
    emoji: '🌆',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#030010', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: 'Inter',
        fontSize: 70,
        color: '#00ffff',
        glow: true,
        glowColor: '#ff00ff',
        animation: 'slide',
        translationColor: '#ff00ff',
        translationSize: 35,
      },
      particles: { enabled: true, count: 600, reactTo: 'bass', color: '#00ffff', size: 0.04 },
      heroShape: {
        enabled: false,
        type: 'torusKnot',
        style: 'solid',
        colorA: '#a855f7',
        colorB: '#22d3ee',
        wireframeColor: '#67e8f9',
        knotP: 2,
        knotQ: 5,
        reactTo: 'bass',
      },
    },
  },
  {
    id: 'quantum-knot',
    name: 'Quantum Knot',
    category: 'Visualizer 3D',
    description: 'Nudo toroidal violeta-cian con glow y wireframe. Impacto máximo para lanzamientos.',
    emoji: '🔮',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#05030f', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 60,
        color: '#ffffff',
        glow: true,
        glowColor: '#a855f7',
        animation: 'fade',
        translationColor: '#67e8f9',
        translationSize: 28,
      },
      particles: { enabled: true, count: 250, reactTo: 'treble', color: '#67e8f9', size: 0.025 },
      heroShape: {
        enabled: true,
        type: 'torusKnot',
        style: 'solid',
        colorA: '#a855f7',
        colorB: '#22d3ee',
        wireframeColor: '#67e8f9',
        knotP: 2,
        knotQ: 5,
        reactTo: 'bass',
      },
    },
  },
  {
    id: 'aurora-flow',
    name: 'Aurora Flow',
    category: 'Visualizer 3D',
    description: 'Nudo esmeralda-azul que fluye con calma. Ideal para lanzamientos ambient y chill.',
    emoji: '🌊',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#020a0a', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 56,
        color: '#e0fdf4',
        glow: true,
        glowColor: '#2dd4bf',
        animation: 'fade',
        translationColor: '#5eead4',
        translationSize: 26,
      },
      particles: { enabled: true, count: 300, reactTo: 'mid', color: '#5eead4', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'torusKnot',
        style: 'solid',
        colorA: '#10b981',
        colorB: '#38bdf8',
        wireframeColor: '#5eead4',
        knotP: 3,
        knotQ: 4,
        reactTo: 'mid',
      },
    },
  },
  {
    id: 'solar-pulse',
    name: 'Solar Pulse',
    category: 'Visualizer 3D',
    description: 'Nudo dorado-magenta de alta energía, pulsando con el kick. Para drops explosivos.',
    emoji: '☀️',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#0a0202', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 64,
        color: '#fff7ed',
        glow: true,
        glowColor: '#f97316',
        animation: 'bounce',
        translationColor: '#fb7185',
        translationSize: 30,
      },
      particles: { enabled: true, count: 350, reactTo: 'bass', color: '#fb923c', size: 0.03 },
      heroShape: {
        enabled: true,
        type: 'torusKnot',
        style: 'solid',
        colorA: '#f97316',
        colorB: '#ec4899',
        wireframeColor: '#fdba74',
        knotP: 2,
        knotQ: 7,
        reactTo: 'bass',
      },
    },
  },
  {
    id: 'burning-heart',
    name: 'Corazón en Llamas',
    category: 'Visualizer 3D',
    description: 'Corazón de brasas ardientes hecho de partículas, para baladas intensas y despecho.',
    emoji: '❤️‍🔥',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#0a0402', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 60,
        color: '#fff4d6',
        glow: true,
        glowColor: '#ff5a1f',
        animation: 'bounce',
        translationColor: '#ffab5e',
        translationSize: 28,
      },
      particles: { enabled: false, count: 200, reactTo: 'bass', color: '#ff8a3d', size: 0.03 },
      heroShape: {
        enabled: true,
        type: 'heart',
        style: 'particles',
        colorA: '#fff4c2',
        colorB: '#ff3b0f',
        wireframeColor: '#ffb703',
        knotP: 2,
        knotQ: 5,
        reactTo: 'bass',
      },
    },
  },
  {
    id: 'mech-heart-engagement',
    name: 'Compromiso Eterno',
    category: 'Corazón Mecánico',
    description: 'Corazón de engranajes dorados que giran y late como una bocina con el bajo. Para propuestas y aniversarios.',
    emoji: '💍',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#0a0602', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#fff2cf',
        glow: true,
        glowColor: '#d4a017',
        animation: 'fade',
        translationColor: '#f0c869',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'mid', color: '#f5d98a', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#ffe9a8',
        colorB: '#b8860b',
        wireframeColor: '#f5d67a',
        knotP: 2,
        knotQ: 5,
        reactTo: 'bass',
      },
    },
  },
  {
    id: 'mech-heart-timeless',
    name: 'Vínculo Eterno',
    category: 'Corazón Mecánico',
    description: 'Mismo mecanismo en plata y platino, para vínculos que no se oxidan. Elegante y frío.',
    emoji: '⚙️',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#04050a', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#eef2ff',
        glow: true,
        glowColor: '#8892a6',
        animation: 'fade',
        translationColor: '#b7c0d8',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'treble', color: '#c7d0e8', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#f0f4ff',
        colorB: '#8892a6',
        wireframeColor: '#c7d0e8',
        knotP: 2,
        knotQ: 5,
        reactTo: 'bass',
      },
    },
  },
  {
    id: 'mech-heart-memories',
    name: 'Recuerdos Compartidos',
    category: 'Corazón Mecánico',
    description: 'Engranajes de cobre envejecido, tono cálido de fotografía antigua. Para nostalgia y recuerdos.',
    emoji: '🕰️',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#0a0603', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#ffe6c2',
        glow: true,
        glowColor: '#b3541e',
        animation: 'bounce',
        translationColor: '#d98c4a',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'mid', color: '#e0a565', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#ffd9b3',
        colorB: '#8b4513',
        wireframeColor: '#d9995c',
        knotP: 2,
        knotQ: 5,
        reactTo: 'mid',
      },
    },
  },
  {
    id: 'mech-heart-heartbeat',
    name: 'Latido Sincronizado',
    category: 'Corazón Mecánico',
    description: 'Engranajes en oro rosa que laten y vibran con cada golpe de bajo, como un pulso compartido.',
    emoji: '💓',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#0a0208', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#ffe3ef',
        glow: true,
        glowColor: '#c2185b',
        animation: 'bounce',
        translationColor: '#ff7fab',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'bass', color: '#ff9ec4', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#ffd6e8',
        colorB: '#c2185b',
        wireframeColor: '#ff9ec4',
        knotP: 2,
        knotQ: 5,
        reactTo: 'bass',
      },
    },
  },
  {
    id: 'mech-heart-first-encounter',
    name: 'Primer Encuentro',
    category: 'Corazón Mecánico',
    description: 'Verde primavera y blanco, la chispa de un encuentro que recién empieza a girar.',
    emoji: '🌱',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#020a04', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#eafff2',
        glow: true,
        glowColor: '#4ade80',
        animation: 'fade',
        translationColor: '#86efac',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'treble', color: '#86efac', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#e8fff0',
        colorB: '#22c55e',
        wireframeColor: '#86efac',
        knotP: 2,
        knotQ: 5,
        reactTo: 'treble',
      },
    },
  },
  {
    id: 'mech-heart-shared-secrets',
    name: 'Secretos Compartidos',
    category: 'Corazón Mecánico',
    description: 'Engranajes en índigo profundo, cerrados como una cerradura que solo dos personas conocen.',
    emoji: '🔐',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#050212', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#ede9fe',
        glow: true,
        glowColor: '#7c3aed',
        animation: 'fade',
        translationColor: '#c4b5fd',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'mid', color: '#c4b5fd', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#d8c9ff',
        colorB: '#4c1d95',
        wireframeColor: '#a78bfa',
        knotP: 2,
        knotQ: 5,
        reactTo: 'mid',
      },
    },
  },
  {
    id: 'mech-heart-growing-affection',
    name: 'Cariño Creciente',
    category: 'Corazón Mecánico',
    description: 'Rosa suave que se intensifica poco a poco, como un cariño que va tomando forma.',
    emoji: '🌸',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#0a0308', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#ffe9f2',
        glow: true,
        glowColor: '#f472b6',
        animation: 'fade',
        translationColor: '#fbcfe8',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'mid', color: '#fbcfe8', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#ffe4ec',
        colorB: '#f472b6',
        wireframeColor: '#fbcfe8',
        knotP: 2,
        knotQ: 5,
        reactTo: 'mid',
      },
    },
  },
  {
    id: 'mech-heart-balance',
    name: 'Equilibrio Perfecto',
    category: 'Corazón Mecánico',
    description: 'Engranajes en turquesa que giran en perfecta sincronía, como dos personas en equilibrio.',
    emoji: '⚖️',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#020a08', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#e6fffb',
        glow: true,
        glowColor: '#2dd4bf',
        animation: 'fade',
        translationColor: '#5eead4',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'mid', color: '#5eead4', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#e0fffa',
        colorB: '#0d9488',
        wireframeColor: '#5eead4',
        knotP: 2,
        knotQ: 5,
        reactTo: 'mid',
      },
    },
  },
  {
    id: 'mech-heart-gentle-touch',
    name: 'Toque Suave',
    category: 'Corazón Mecánico',
    description: 'Lavanda claro y delicado, para lo que se siente pero apenas se dice.',
    emoji: '🤍',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#08050f', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#f5ecff',
        glow: true,
        glowColor: '#c084fc',
        animation: 'fade',
        translationColor: '#e9d5ff',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'treble', color: '#e9d5ff', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#f3e8ff',
        colorB: '#9333ea',
        wireframeColor: '#e9d5ff',
        knotP: 2,
        knotQ: 5,
        reactTo: 'treble',
      },
    },
  },
  {
    id: 'mech-heart-deep-trust',
    name: 'Confianza Profunda',
    category: 'Corazón Mecánico',
    description: 'Azul marino sólido, engranajes que giran seguros y sin dudar. Para lo que ya está probado.',
    emoji: '🛡️',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#020308', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#e6f0ff',
        glow: true,
        glowColor: '#3b82f6',
        animation: 'fade',
        translationColor: '#93c5fd',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'bass', color: '#93c5fd', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#dbeafe',
        colorB: '#1e3a8a',
        wireframeColor: '#60a5fa',
        knotP: 2,
        knotQ: 5,
        reactTo: 'bass',
      },
    },
  },
  {
    id: 'mech-heart-written-vows',
    name: 'Votos Escritos',
    category: 'Corazón Mecánico',
    description: 'Marfil y tinta dorada, como una promesa firmada. Para bodas y aniversarios.',
    emoji: '📜',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#0a0803', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#fffbe6',
        glow: true,
        glowColor: '#eab308',
        animation: 'fade',
        translationColor: '#fde68a',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'mid', color: '#fde68a', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#fffbea',
        colorB: '#a16207',
        wireframeColor: '#facc15',
        knotP: 2,
        knotQ: 5,
        reactTo: 'mid',
      },
    },
  },
  {
    id: 'mech-heart-pair-bond',
    name: 'Vínculo de Pareja',
    category: 'Corazón Mecánico',
    description: 'Vino tinto profundo, dos engranajes engranados que no giran el uno sin el otro.',
    emoji: '🔗',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#0a0203', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#ffe6ea',
        glow: true,
        glowColor: '#b91c1c',
        animation: 'bounce',
        translationColor: '#fca5a5',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'bass', color: '#fca5a5', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#ffe0e6',
        colorB: '#7f1d1d',
        wireframeColor: '#f87171',
        knotP: 2,
        knotQ: 5,
        reactTo: 'bass',
      },
    },
  },
  {
    id: 'mech-heart-shared-dreams',
    name: 'Sueños Compartidos',
    category: 'Corazón Mecánico',
    description: 'Azul medianoche y plata estelar, para lo que se planea juntos mirando el techo de noche.',
    emoji: '💭',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#03040a', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#eef2ff',
        glow: true,
        glowColor: '#94a3b8',
        animation: 'fade',
        translationColor: '#cbd5e1',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'treble', color: '#cbd5e1', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#e6ecff',
        colorB: '#1e293b',
        wireframeColor: '#94a3b8',
        knotP: 2,
        knotQ: 5,
        reactTo: 'treble',
      },
    },
  },
  {
    id: 'mech-heart-tender-moments',
    name: 'Momentos Tiernos',
    category: 'Corazón Mecánico',
    description: 'Durazno y coral suave, para las pequeñas escenas que se quedan grabadas.',
    emoji: '🕊️',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#0a0603', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#fff2e8',
        glow: true,
        glowColor: '#fda4af',
        animation: 'fade',
        translationColor: '#fecdd3',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'mid', color: '#fecdd3', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#fff1e6',
        colorB: '#fb7185',
        wireframeColor: '#fda4af',
        knotP: 2,
        knotQ: 5,
        reactTo: 'mid',
      },
    },
  },
  {
    id: 'mech-heart-fluttering-hearts',
    name: 'Corazones Aleteantes',
    category: 'Corazón Mecánico',
    description: 'Fucsia y magenta vibrantes, engranajes ligeros que aletean como mariposas en el estómago.',
    emoji: '🦋',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#0a0209', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#ffe9fc',
        glow: true,
        glowColor: '#e879f9',
        animation: 'bounce',
        translationColor: '#f0abfc',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'treble', color: '#f0abfc', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#ffe0fb',
        colorB: '#c026d3',
        wireframeColor: '#e879f9',
        knotP: 2,
        knotQ: 5,
        reactTo: 'treble',
      },
    },
  },
  {
    id: 'mech-heart-beloved-faces',
    name: 'Rostros Amados',
    category: 'Corazón Mecánico',
    description: 'Ámbar cálido, del color de la luz que queda cuando piensas en esa cara que ya conoces de memoria.',
    emoji: '😍',
    isPremium: true,
    config: {
      background: { type: 'color', color: '#0a0602', blur: 0, opacity: 1 },
      lyricStyle: {
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 58,
        color: '#fff6e0',
        glow: true,
        glowColor: '#f59e0b',
        animation: 'bounce',
        translationColor: '#fcd34d',
        translationSize: 27,
      },
      particles: { enabled: false, count: 150, reactTo: 'bass', color: '#fcd34d', size: 0.02 },
      heroShape: {
        enabled: true,
        type: 'gearHeart',
        style: 'particles',
        colorA: '#fff4d9',
        colorB: '#c2650a',
        wireframeColor: '#f59e0b',
        knotP: 2,
        knotQ: 5,
        reactTo: 'bass',
      },
    },
  },
]
